%YAML 1.2
---
# A four bars mecahnism
# Degrees of freedom in q=[x1 y1 x2 y2]^T
# Modeled in Natural coordinates:
#
#             2:(q3,q4)
#               +---------o
#               |       (xb,yb)
#               |
#               |
#     o---------+ 1:(q1,q2)
#    (xa,ya)
#
parameters:
  L: 1.0  # length [m]
  xb: 4.0
points:
  # 0 (="A")
  - {x: 0, y: 0, fixed: true}
  # 1
  - { x: L, y: 0 }
  # 2
  - { x: L, y: 2*L }
  # 3 (="B")
  - { x: xb, y: 0, fixed: true }
planar_bodies:
  # 0
  - points: [0, 1]
    length: L
    mass: 1.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 1
  - points: [1, 2]
    length: 2*L
    mass: 2.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 3
  - points: [2, 3]
    length: auto
    mass: 4.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
