%YAML 1.2
---
# A four bars mecahnism, with crank angle as relative coordinate.
# Degrees of freedom in q=[x1 y1 x2 y2 q5]^T
# Modeled in Natural coordinates plus one relative angle coordinate
# at the left-hand side fixed end.
#
#             2:(q3,q4)
#               +---------o
#               |       (xb,yb)
#               |
#               |
#     o---------+ 1:(q1,q2)
#    (xa,ya)
#
#  - q5: Angle (xa,ya)-(q1,q2)
#
points:
  # 0 (="A")
  - {x: 0, y: 0, fixed: true}
  # 1
  - { x: 1.0, y: 0 }
  # 2
  - { x: 1.0, y: 2.0 }
  # 3 (="B")
  - { x: 4.0, y: 0, fixed: true }
planar_bodies:
  # 0
  - points: [0, 1]
    length: 1.0
    mass: 1.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 1
  - points: [1, 2]
    length: 2.0
    mass: 2.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 3
  - points: [2, 3]
    length: sqrt(2.0^2 + 3^2)
    mass: 4.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
# Relative coordinates:
relative_coordinates:
  # 0
  - type: RelativeAngleAbsoluteDOF
    points: [0, 1]
