%YAML 1.2
---
# Pendulum with a ternary link
points:
  # 0
  - x: 0
    y: 0
    fixed: true
  # 1
  - { x: 5.0, y: 0 }
  # 2
  - { x: 5+3, y: 0+4 }
  # 3
  - { x: 5+3, y: 0-4 }
  # 4
  - { x: 5+3+2, y: 0+4+1 }
  # 5
  - { x: 5+3+5, y: 0-4+0 }
planar_bodies:
  # 0
  - points: [0, 1]
    length: auto
    mass: 2.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 1
  - points: [1, 2, 3]
    #length: auto  # length is ignored for 3-ary or higher-order bodies
    mass: 3.0
    I0: (1/3)*mass*length12^2
    cog: [0.5*length12, -0.5*length12]
  # 2
  - points: [2, 4]
    length: auto
    mass: 1.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 3
  - points: [3, 5]
    length: auto
    mass: 2.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
