%YAML 1.2
---
# Pendulum with a quaternary link.
points:
  - { x: 0.0, y: 0.0, fixed: true } # 0
  - { x: 2.0, y: 0.0 } # 1
  - { x: 2.0, y: -1.0 } # 2
  - { x: 0.0, y: -1.0 } # 3
  - { x: x1+1.0, y: y1 } # 4
  - { x: x2+2.0, y: y2 } # 5
  - { x: x3, y: y3-1.0 } # 6
planar_bodies:
  # 0
  - points: [0, 1, 2, 3]
    # length: auto  # length is ignored for 3-ary or higher-order bodies
    mass: 2.0
    I0: (1/3)*mass*length12^2
    cog: [0.5*length12, 0.5*length14]
  # 1
  - points: [1, 4]
    length: auto
    mass: 1.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 2
  - points: [2, 5]
    length: auto
    mass: 1.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
  # 3
  - points: [3, 6]
    length: auto
    mass: 2.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
