%YAML 1.2
---
# Pendulum
points:
  # 0
  - x: 0
    y: 0
    fixed: true
  # 1
  - { x: 2.0*cos(deg2rad(45.0)), y: 2.0*sin(deg2rad(45.0)) }
planar_bodies:
  # 0
  - points: [0, 1]
    length: 2.0
    mass: 5.0
    I0: (1/3)*mass*length^2
    cog: [0.5*length, 0.0]
