version: 2
jobs:
  gcc-u18.04:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt update
            export DEBIAN_FRONTEND=noninteractive
            apt install software-properties-common -yq
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt install build-essential g++ cmake -yq
            apt install libmrpt-dev libgtsam-dev -yq
            apt install libboost-timer-dev -yq
      - checkout
      - run:
          name: Generate cmake files
          command: |
            cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
  gcc-u20.04:
    docker:
      - image: ubuntu:focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt update
            export DEBIAN_FRONTEND=noninteractive
            apt install software-properties-common -yq
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt install build-essential g++ cmake -yq
            apt install libmrpt-dev libgtsam-dev -yq
            apt install libboost-timer-dev -yq
      - checkout
      - run:
          name: Generate cmake files
          command: |
            cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
  clang-u18.04:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt update
            export DEBIAN_FRONTEND=noninteractive
            apt install software-properties-common -yq
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt install build-essential clang cmake -yq
            apt install cmake libmrpt-dev libgtsam-dev -yq
            apt install libboost-timer-dev -yq
      - checkout
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
          environment:
            CC: /usr/bin/clang
            CXX: /usr/bin/clang++
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
  clang-u20.04:
    docker:
      - image: ubuntu:focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt update
            export DEBIAN_FRONTEND=noninteractive
            apt install software-properties-common -yq
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt install build-essential clang cmake -yq
            apt install cmake libmrpt-dev libgtsam-dev -yq
            apt install libboost-timer-dev -yq
      - checkout
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
          environment:
            CC: /usr/bin/clang
            CXX: /usr/bin/clang++
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
workflows:
  version: 2
  build:
    jobs:
      - gcc-u18.04
      - gcc-u20.04
      - clang-u18.04
      - clang-u20.04
